import Foundation

/// KuraKeys/ ローカル Swift Package を生成する
struct CodeGenerator {
    let config: KuraConfig
    let encoder: KuraEncoder

    // MARK: - エントリポイント

    func generate(secrets: [String: String], at basePath: String) throws {
        let packageRoot = (basePath as NSString)
            .appendingPathComponent(config.importName)
        let sourcesDir = ((packageRoot as NSString)
            .appendingPathComponent("Sources") as NSString)
            .appendingPathComponent(config.importName)

        try FileManager.default.createDirectory(
            atPath: sourcesDir,
            withIntermediateDirectories: true
        )

        try write(makePackageSwift(), to: packageRoot, filename: "Package.swift")
        try write(makeReadme(), to: packageRoot, filename: "README.md")
        try write(makeKeysSwift(secrets: secrets), to: sourcesDir, filename: "\(config.importName).swift")

        print("✅  Generated \(config.importName) at \(packageRoot)")
    }

    // MARK: - Package.swift の生成

    private func makePackageSwift() -> String {
        """
        // swift-tools-version: 5.6

        // AUTO-GENERATED by Kura (https://github.com/CH3COOH/Kura) — DO NOT EDIT

        import PackageDescription

        let package = Package(
            name: "\(config.importName)",
            platforms: [.iOS(.v14), .macOS(.v12)],
            products: [
                .library(name: "\(config.importName)", targets: ["\(config.importName)"]),
            ],
            targets: [
                .target(name: "\(config.importName)", path: "Sources/\(config.importName)"),
            ]
        )
        """
    }

    // MARK: - README.md の生成

    private func makeReadme() -> String {
        """
        # \(config.importName)

        DO NOT EDIT THIS PACKAGE MANUALLY.

        It is auto-generated by [Kura](https://github.com/CH3COOH/Kura). Run `swift run --package-path BuildTools kura-generator` to regenerate.
        """
    }

    // MARK: - KuraKeys.swift の生成

    private func makeKeysSwift(secrets: [String: String]) throws -> String {
        let decl = config.swiftDeclaration
        var lines: [String] = [
            "// AUTO-GENERATED by Kura (https://github.com/CH3COOH/Kura) — DO NOT EDIT",
            "// swiftlint:disable all",
            "import Foundation",
            "",
        ]

        lines += makeDecodeFunc()
        lines += [""]

        let hasAnySecrets = !config.globalSecrets.isEmpty || !config.environments.isEmpty
        guard hasAnySecrets else { return lines.joined(separator: "\n") }

        // ArkanaKeys.Global.xxx / ArkanaKeys.Debug.xxx 形式でアクセスできるよう
        // 外側の enum を共有し、Global・環境名を入れ子にする
        var seenNestedNames: [String: String] = [:] // 入れ子 enum 名 → 由来（衝突検出用）

        lines += ["\(decl) enum \(config.importName) {"]

        // グローバルシークレット → Global
        if !config.globalSecrets.isEmpty {
            seenNestedNames["Global"] = "global_secrets"
            lines += ["    \(decl) enum Global {"]
            lines += try makeKeyProperties(keys: config.globalSecrets, secrets: secrets, decl: decl, indent: "        ")
            lines += ["    }", ""]
        }

        // 環境別シークレット → Debug / Release など
        for (envName, keys) in config.environments.sorted(by: { $0.key < $1.key }) {
            let nestedName = pascalCase(envName)
            guard !nestedName.isEmpty else {
                throw KuraError.invalidConfig(
                    "Environment name '\(envName)' cannot be converted to a Swift identifier"
                )
            }
            // `Type` / `Protocol` はバッククォートで宣言できても、
            // `KuraKeys.Type.key` がメタタイプ参照と衝突して呼び出せないため拒否する
            guard nestedName != "Type", nestedName != "Protocol" else {
                throw KuraError.invalidConfig(
                    "Environment name '\(envName)' generates nested enum '\(nestedName)', "
                        + "which cannot be referenced in Swift. Rename the environment."
                )
            }
            if let existing = seenNestedNames[nestedName] {
                throw KuraError.invalidConfig(
                    "Environment '\(envName)' and \(existing) both generate nested enum '\(nestedName)'"
                )
            }
            seenNestedNames[nestedName] = "environment '\(envName)'"
            lines += ["    \(decl) enum \(escapeKeywordIfNeeded(nestedName)) {"]
            lines += try makeKeyProperties(keys: keys, secrets: secrets, decl: decl, indent: "        ")
            lines += ["    }", ""]
        }

        lines += ["}", ""]

        return lines.joined(separator: "\n")
    }

    // MARK: - プロパティの生成

    private func makeKeyProperties(
        keys: [String],
        secrets: [String: String],
        decl: String,
        indent: String = "    "
    ) throws -> [String] {
        var seenPropNames: [String: String] = [:] // プロパティ名 → 元のキー（衝突検出用）
        var lines: [String] = []
        for key in keys {
            guard let value = secrets[key] else { continue }
            let propName = config.preserveKeyCase ? sanitizeIdentifier(key) : camelCase(key)
            guard !propName.isEmpty else {
                throw KuraError.invalidConfig(
                    "Key '\(key)' cannot be converted to a Swift identifier"
                )
            }
            if let existing = seenPropNames[propName] {
                throw KuraError.invalidConfig(
                    "Keys '\(existing)' and '\(key)' both map to Swift property '\(propName)'"
                )
            }
            seenPropNames[propName] = key
            lines += makeKeyProperty(propName: propName, value: value, decl: decl, indent: indent)
        }
        return lines
    }

    private func makeKeyProperty(
        propName: String,
        value: String,
        decl: String,
        indent: String
    ) -> [String] {
        let encoded = encoder.encode(value)
        let escaped = escapeKeywordIfNeeded(propName)
        return [
            "\(indent)\(decl) static var \(escaped): String {",
            "\(indent)    let encoded: [UInt8] = \(encoded.encodedBytesLiteral)",
            "\(indent)    let salt: [UInt8]    = \(encoded.saltLiteral)",
            "\(indent)    return _kuraDecrypt(encoded, salt: salt)",
            "\(indent)}",
        ]
    }

    // MARK: - デコード関数の生成

    private func makeDecodeFunc() -> [String] {
        [
            "private func _kuraDecrypt(_ encoded: [UInt8], salt: [UInt8]) -> String {",
            "    let bytes = encoded.enumerated().map { idx, byte -> UInt8 in",
            "        byte ^ salt[idx % salt.count]",
            "    }",
            "    return String(bytes: bytes, encoding: .utf8) ?? \"\"",
            "}",
        ]
    }

    // MARK: - ユーティリティ

    /// "_" "-" "空白" を単語区切りとして分割する
    private func splitWords(_ key: String) -> [String] {
        key.lowercased()
            .split(whereSeparator: { $0 == "_" || $0 == "-" || $0 == " " })
            .map(String.init)
    }

    /// SOME_KEY → someKey、APIKEY → apikey
    private func camelCase(_ key: String) -> String {
        let parts = splitWords(key)
        guard let first = parts.first else { return sanitizeIdentifier(key.lowercased()) }
        let joined = first + parts.dropFirst().map(\.capitalized).joined()
        return sanitizeIdentifier(joined)
    }

    /// some-env → SomeEnv
    private func pascalCase(_ key: String) -> String {
        let joined = splitWords(key).map(\.capitalized).joined()
        return sanitizeIdentifier(joined)
    }

    /// Swift識別子として不正な文字を除去し、数字始まりの場合は "_" を付与する
    private func sanitizeIdentifier(_ raw: String) -> String {
        let filtered = raw.filter { $0.isLetter || $0.isNumber || $0 == "_" }
        guard let first = filtered.first else { return filtered }
        return first.isNumber ? "_" + filtered : filtered
    }

    /// Swiftの予約語（DEFAULT → `default` など）をバッククォートでエスケープする
    private static let swiftKeywords: Set<String> = [
        "as", "associatedtype", "break", "case", "catch", "class", "continue",
        "default", "defer", "deinit", "do", "else", "enum", "extension",
        "fallthrough", "false", "fileprivate", "for", "func", "guard", "if",
        "import", "in", "init", "inout", "internal", "is", "let", "nil",
        "open", "operator", "private", "protocol", "public", "repeat",
        "rethrows", "return", "self", "static", "struct", "subscript",
        "super", "switch", "throw", "throws", "true", "try", "typealias",
        "var", "where", "while",
        // 大文字始まりの予約語（環境名の pascalCase 変換で衝突しうる）
        "Any", "Self",
    ]

    private func escapeKeywordIfNeeded(_ identifier: String) -> String {
        Self.swiftKeywords.contains(identifier) ? "`\(identifier)`" : identifier
    }

    private func write(_ content: String, to dir: String, filename: String) throws {
        let path = (dir as NSString).appendingPathComponent(filename)
        try content.write(toFile: path, atomically: true, encoding: .utf8)
    }
}
