import Foundation

/// KuraKeys/ ローカル Swift Package を生成する
struct CodeGenerator {
    let config: KuraConfig
    let encoder: KuraEncoder

    // MARK: - エントリポイント

    func generate(secrets: [String: String], at basePath: String) throws {
        let packageRoot = (basePath as NSString)
            .appendingPathComponent(config.importName)
        let sourcesDir = ((packageRoot as NSString)
            .appendingPathComponent("Sources") as NSString)
            .appendingPathComponent(config.importName)

        try FileManager.default.createDirectory(
            atPath: sourcesDir,
            withIntermediateDirectories: true
        )

        try write(makePackageSwift(), to: packageRoot, filename: "Package.swift")
        try write(makeKeysSwift(secrets: secrets), to: sourcesDir, filename: "\(config.importName).swift")

        print("✅  Generated \(config.importName) at \(packageRoot)")
    }

    // MARK: - Package.swift の生成

    private func makePackageSwift() -> String {
        """
        // swift-tools-version: 5.6
        // AUTO-GENERATED by Kura (https://github.com/CH3COOH/Kura) — DO NOT EDIT
        import PackageDescription

        let package = Package(
            name: "\(config.importName)",
            platforms: [.iOS(.v14), .macOS(.v12)],
            products: [
                .library(name: "\(config.importName)", targets: ["\(config.importName)"]),
            ],
            targets: [
                .target(name: "\(config.importName)", path: "Sources/\(config.importName)"),
            ]
        )
        """
    }

    // MARK: - KuraKeys.swift の生成

    private func makeKeysSwift(secrets: [String: String]) -> String {
        let decl = config.swiftDeclaration
        var lines: [String] = [
            "// AUTO-GENERATED by Kura (https://github.com/CH3COOH/Kura) — DO NOT EDIT",
            "// swiftlint:disable all",
            "import Foundation",
            "",
        ]

        lines += makeDecodeFunc()
        lines += [""]

        // グローバルシークレット
        if !config.globalSecrets.isEmpty {
            lines += ["\(decl) enum \(config.importName) {"]
            for key in config.globalSecrets {
                guard let value = secrets[key] else { continue }
                lines += makeKeyProperty(key: key, value: value, decl: decl, indent: "    ")
            }
            lines += ["}", ""]
        }

        // 環境別シークレット
        for (envName, keys) in config.environments.sorted(by: { $0.key < $1.key }) {
            let enumName = pascalCase(envName)
            lines += ["\(decl) enum \(config.importName)\(enumName) {"]
            for key in keys {
                guard let value = secrets[key] else { continue }
                lines += makeKeyProperty(key: key, value: value, decl: decl, indent: "    ")
            }
            lines += ["}", ""]
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - プロパティの生成

    private func makeKeyProperty(
        key: String,
        value: String,
        decl: String,
        indent: String
    ) -> [String] {
        let encoded = encoder.encode(value)
        let propName = camelCase(key)
        return [
            "\(indent)\(decl) static var \(propName): String {",
            "\(indent)    let encoded: [UInt8] = \(encoded.encodedBytesLiteral)",
            "\(indent)    let salt: [UInt8]    = \(encoded.saltLiteral)",
            "\(indent)    return _kuraDecrypt(encoded, salt: salt)",
            "\(indent)}",
        ]
    }

    // MARK: - デコード関数の生成

    private func makeDecodeFunc() -> [String] {
        [
            "private func _kuraDecrypt(_ encoded: [UInt8], salt: [UInt8]) -> String {",
            "    let bytes = encoded.enumerated().map { idx, byte -> UInt8 in",
            "        byte ^ salt[idx % salt.count]",
            "    }",
            "    return String(bytes: bytes, encoding: .utf8) ?? \"\"",
            "}",
        ]
    }

    // MARK: - ユーティリティ

    /// "_" "-" "空白" を単語区切りとして分割する
    private func splitWords(_ key: String) -> [String] {
        key.lowercased()
            .split(whereSeparator: { $0 == "_" || $0 == "-" || $0 == " " })
            .map(String.init)
    }

    /// SOME_KEY → someKey
    private func camelCase(_ key: String) -> String {
        let parts = splitWords(key)
        guard let first = parts.first else { return sanitizeIdentifier(key.lowercased()) }
        let joined = first + parts.dropFirst().map(\.capitalized).joined()
        return sanitizeIdentifier(joined)
    }

    /// some-env → SomeEnv
    private func pascalCase(_ key: String) -> String {
        let joined = splitWords(key).map(\.capitalized).joined()
        return sanitizeIdentifier(joined)
    }

    /// Swift識別子として不正な文字を除去し、数字始まりの場合は "_" を付与する
    private func sanitizeIdentifier(_ raw: String) -> String {
        let filtered = raw.filter { $0.isLetter || $0.isNumber || $0 == "_" }
        guard let first = filtered.first else { return filtered }
        return first.isNumber ? "_" + filtered : filtered
    }

    private func write(_ content: String, to dir: String, filename: String) throws {
        let path = (dir as NSString).appendingPathComponent(filename)
        try content.write(toFile: path, atomically: true, encoding: .utf8)
    }
}
